---
- name: Create installation config file
  ansible.builtin.template:
    src: templates/code42.deployment.properties
    dest: '/tmp/code42.deployment.properties'
    mode: '0664'

- name: Create code42 extract directory
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  loop:
    - '{{ download }}'
    - '{{ extract }}'

- name: Download code42 package
  become: no
  command: aws s3 cp {{ s3_uri }} {{ extract }} --quiet
  environment:
    AWS_ACCESS_KEY_ID: '{{ aws_access_key_id }}'
    AWS_SECRET_ACCESS_KEY: '{{ aws_secret_access_key }}'
  register: c42dl
  args:
    creates: '{{ extract }}/{{ installer }}'

- name: Download output
  debug:
    msg: 'code42 bucket: {{ c42dl.stdout }}'

- name: check code42 install dir
  stat:
    path: /opt/code42-aat
  register: code42_installed

- name: Install code42 package
  become: yes
  when: not code42_installed.stat.exists
  apt:
    deb: '{{ extract }}/{{ installer }}'
